##
# cloudbuild.yaml
#
# Usage:
#   export COMMIT_SHA=$(git rev-parse --short HEAD)
##
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/xrplgraph-server:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/xrplgraph-server:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'xrplgraph-server'
  - '--image'
  - 'gcr.io/$PROJECT_ID/xrplgraph-server:latest'
  - '--region'
  - 'us-central1'
images: ['gcr.io/$PROJECT_ID/xrplgraph-server:latest']
options:
  substitutionOption: ALLOW_LOOSE
timeout: 900s
